---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: autoscale-go-1
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: rps  # concurrency
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/target: "8" # Target: in-flight-requests per pod.
    spec:
      containerConcurrency: 4
      containers:
      - image: gcr.io/knative-samples/autoscale-go:0.1
        resources:
          requests:
            memory: "5Gi"
            cpu: "3"
          limits:
            memory: "5Gi"
            cpu: "3"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: autoscale-go-2
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: rps  # concurrency
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/target: "8" # Target: in-flight-requests per pod.
    spec:
      containerConcurrency: 4
      containers:
      - image: gcr.io/knative-samples/autoscale-go:0.1
        resources:
          requests:
            memory: "5Gi"
            cpu: "3"
          limits:
            memory: "5Gi"
            cpu: "3"


